### ISSUE TITLE
Blinking LED (Pico) - SD Module Power Problems

### ISSUE THREAD

**Issue by BRIK1111** [dangiu/PicoMemcard#36]
I built the original PicoMemcard and everything was fine. I upgraded to the plus using the same SD card module as the guide and receive the blinking LED 99% of the time. Strangely, there have been one or two times when the test memory card file provided does appear.

I uploaded the new uf2 file, the SD card appears through the Pico on my computer for file transfer - so I'm confident the wiring is correct and that the SD card expansion module works. I've also measured the voltage on the module as it's plugged into the PlayStation. 3.5v more or less on the dot. I've also tried the bodge wire fix directly to pin 36 from the other threads. With that installed, I instead measure just under 3v. Could the module not have the power range that's advertised? 

Edit: Just want to add that I've tried multiple SD cards.

**Comment by dangiu** [comment]
Since the SD card pops up when connected to the PC we know that the SD module and microSD card are both functional. To test whether this is a power issue I would suggest trying the following:
- Make sure that when connected to the PC the SD card pops up
- Tape off the contact that provides power from the PSX to PicoMemcard
- Power PicoMemcard using a USB phone charger (do not use a USB port of a PC otherwise it will enter in transfer mode)
- Connect it to the PSX and see if it gets detected when powered this way

Make sure to only disconnect the power pin and not the ground pin (to the PSX) otherwise they will not be able to communicate properly.
Btw which PSX model do you have?
Sorry for the late reply, let me know how it goes :)

**Comment by BRIK1111** [comment]
Yep, taping off the 3.3v and plugging in a charger worked. Does this indicate that the module doesn't work as well on 3.3v as advertised? 

The PS1 models I've tried are the SCPH-102 and the SCPH-7502 (both PAL).

**Comment by dangiu** [comment]
Yup, that is likely the reason why. Are you able to try with another SD module? Btw could you post a picture of your current one just for reference?

**Comment by BRIK1111** [comment]
I've ordered another, this time from a reputable seller as opposed to eBay. I'll report back if it works. 

Here is a photo of the original:
![PXL_20221214_132928634](https://user-images.githubusercontent.com/92701258/207609780-e71094f4-ffb2-4841-a051-9306e2ce2146.jpg)

**Comment by dangiu** [comment]
Aesthetically is very similar to the one I was using, I'll see if I still have it and compare the part number of the power regulator.

**Comment by BRIK1111** [comment]
I tried another that looked nearly identical (it's just missing the text that says "HW-125") and had the same issue! But again, taping off the 3v contact and plugging in a 5v power supply worked. Pretty disappointing since this was also advertised as specifically being compatible with 3v.

![PXL_20221231_084149672 MP](https://user-images.githubusercontent.com/92701258/210130882-ae1c221c-0203-4c72-be35-f529b0c425c0.jpg)

So, I bought this since it has a dedicated contact point for 3v power: https://www.jaycar.com.au/arduino-compatible-sd-card-interface-module/p/XC4386?pos=1&queryId=1f13511ba25c52c03adf5557b7537b72&sort=relevance

And it works! It's a shame that it's so big since it uses a full-size SD card, but I'll take it as a win. 

![DSC01254](https://user-images.githubusercontent.com/92701258/210130924-7d40b014-205a-4dca-b8f5-e1146c45b147.JPG)

**Comment by dangiu** [comment]
I'm glad that at least now it works, I've changed the title of the issue so that it may be easier to find for other people that have the same problem. Happy new year!

**Comment by dazzaXx** [comment]
Hi, I just wanted to add onto this issue here as I also had the exact same problem. Instead of looking for another module, I learn't that if you bridge pin 2 and 3 on the regulator, it bypasses it so you can use 3v. Simple fix. All I did to bridge them was put a blob of solder in between them. Although it probably will break if you bridge it and  also attempt to use 5v.

![1](https://github.com/dangiu/PicoMemcard/assets/48131734/14665035-ef41-419d-af11-642bea5d2d31)
