### ISSUE TITLE
debug scenario

### ISSUE THREAD

**Issue by madmai** [dangiu/PicoMemcard#39]
I've changed some code in your project, it's a small change, but I can't check if it works well, I'm a newbie, how can I put a debugging scenario to show error messages, thank you again I'm a newbie. for example, show messages in the log console or something like that, I repeat, thanks in advance, greetings

**Comment by dangiu** [comment]
It's difficult to explain it step by step in a github issue. I suggest you start looking more into the Raspberry Pi Pico documentation, there are ways to redirect the printf output to UART in order to provide some sort of output in the terminal. Also there are ways to step through the code like you would normally do with a standard program.

https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html
