### ISSUE TITLE
RP2040-ZERO support?

### ISSUE THREAD

**Issue by A-Ibrahim** [dangiu/PicoMemcard#6]
please can you do PCB for RP2040-zero?
https://www.waveshare.com/wiki/RP2040-Zero

**Comment by Jumpingmanjim** [comment]
[I think this guy already got it working](https://github.com/dangiu/PicoMemcard/issues/3)

**Comment by A-Ibrahim** [comment]
Yes, thanks a lot bro

**Comment by dangiu** [comment]
I've created and tested a PCB slightly modified to accomodate a RP2040-Zero (and future proofed for the SD expansion board).
I've also designed a smaller version (right side of the image) that can be dropped right into the memory card shell creating a plug and play solution right away. I've yet to test the small design though, but it won't support the additional SD expansion board due to space constraints.

![RP2040-Zero](https://user-images.githubusercontent.com/5966597/179366595-9d656219-9ea9-4ad9-8dee-b0bde7d61e36.png)
